# Regression drill

This is a simple regression drill. Try to write the minimal code to finish the pipeline.

1. Load and store the data from the existing `diabetes` dataset from `scikit-learn`.

In [112]:

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets

diabetes = sklearn.datasets.load_diabetes(as_frame=True)

df = diabetes["frame"]

df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

2. Explore your data by viewing and calculating some basic statistical details like percentiles and mean. Use the pandas library!

In [113]:



np.mean(df)
np.median(df)
np.quantile(df, np.linspace(0,1,5))
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,442.000000
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17,152.133484
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,77.093005
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01,25.000000
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02,87.000000
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03,140.500000
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02,211.500000
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01,346.000000

3. Create some scatter plots or any other kind of plots that help you understand the data.

In [ ]:
features = df.columns[:-1] 
# Create a figure with subplots
fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(15, 20))

# Flatten the axes array for easy iteration
axes = axes.flatten()


# Create scatter plots for each feature
for i, feature in enumerate(features):
    axes[i].scatter(df[feature], df["target"], color='blue', marker='o')
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel('Disease Progression')
    axes[i].set_title(f'{feature} vs Disease Progression')

plt.tight_layout()
plt.show()

In [ ]:
import seaborn as sns
# Create a figure with subplots
fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(15, 20))

# Flatten the axes array for easy iteration
axes = axes.flatten()

# Create scatter plots for each feature
for i, feature in enumerate(features):
    sns.boxplot(x=df[feature], ax=axes[i])
    axes[i].set_xlabel(feature)
    axes[i].set_title(f'Distribution of {feature}')

plt.tight_layout()
plt.show()

In [ ]:
import seaborn as sns

# Create a pair plot for the first few features and the target variable
sns.pairplot(df.iloc[:, :10].assign(target=df['target']), diag_kind='kde')
plt.show()

In [ ]:
# For demonstration, let's create a categorical feature
df['age_group'] = pd.cut(df['age'], bins=20 )

# Create a bar plot to show the average disease progression for each age group
df.groupby('age_group')['target'].mean().plot(kind='bar', color='blue')
plt.xlabel('Age Group')
plt.ylabel('Average Disease Progression')
plt.title('Average Disease Progression by Age Group')
plt.show()

4. Create a model and compute the accuracy of its predictions.

In [122]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1].values

y = np.array(df["target"])
X.shape
y.shape


X_train, X_test, y_train, y_test = train_test_split(X, y , random_state=42, test_size=0.2)


regressor = LinearRegression().fit(X_train, y_train)
regressor.score(X_train, y_train)

0.4526027629719197

In [123]:
regressor.predict(X_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59678023,
       130.70432536, 202.18534537, 171.13039501, 164.91423047,
       124.72472569, 144.81030894, 181.99635452, 199.41369642,
       234.21436188, 145.95665512,  79.86703276, 157.36941275,
       192.74412541, 208.89814032, 158.58722555, 206.02195855,
       107.47971675, 140.93598906,  54.82129332,  55.92573195,
       115.01180018,  78.95584188,  81.56087285,  54.37997256,
       166.2543518 ])

In [124]:
regressor.score(X_test, y_test)

0.4526027629719197

5. Play with other datasets such as `boston` from scikit-learn, or find datasets online such as [this one](https://www.kaggle.com/dmvreddy91/usahousing) or [this one](https://www.kaggle.com/hellbuoy/car-price-prediction). Careful, not all the datasets are appropriate for regression, so make sure to specify that in your search.